import pyrr

YAW = 0
PITCH = 0
SENSITIVITY = 0.3
CAM_RAD = 0
CAM_HEIGHT = 0
CENTER_POINT = pyrr.Vector3([0.0, 0.0, 0.0])
INVERT = True
FIRST_MOUSE = True 
TEXTURE_FOLDER = 'textures'
W_WIDTH = 1280
W_HEIGHT = 720
FOV = 80
GRID_SIZE = (5, 5)  
TILE_SPACING = 0.9
WALK_SPEED = 0.02
SPRINT_MULTIPLIER = 2.0
DRAW_DISTANCE = 1
VIEW_LOC = None 
DESIRED_FPS = 200
